/*
File:   gy_defines_check.h
Author: Taylor Robbins
Date:   09\14\2021
*/

#ifndef _GY_DEFINES_CHECK_H
#define _GY_DEFINES_CHECK_H

#if !defined(WINDOWS_COMPILATION) && !defined(OSX_COMPILATION) && !defined(LINUX_COMPILATION) && !defined(WASM_COMPILATION) && !defined(PLAYDATE_COMPILATION) && !defined(ORCA_COMPILATION)
#error Either WINDOWS_COMPILATION, OSX_COMPILATION, LINUX_COMPILATION, WASM_COMPILATION, PLAYDATE_COMPILATION, or ORCA_COMPILATION must be defined before including anything from Common
#endif

#ifdef WINDOWS_COMPILATION
#undef WINDOWS_COMPILATION
#define WINDOWS_COMPILATION 1
#else
#define WINDOWS_COMPILATION 0
#endif

#ifdef OSX_COMPILATION
#undef OSX_COMPILATION
#define OSX_COMPILATION 1
#else
#define OSX_COMPILATION 0
#endif

#ifdef LINUX_COMPILATION
#undef LINUX_COMPILATION
#define LINUX_COMPILATION 1
#else
#define LINUX_COMPILATION 0
#endif

#ifdef WASM_COMPILATION
#undef WASM_COMPILATION
#define WASM_COMPILATION 1
#else
#define WASM_COMPILATION 0
#endif

#ifdef PLAYDATE_COMPILATION
#undef PLAYDATE_COMPILATION
#define PLAYDATE_COMPILATION 1
#else
#define PLAYDATE_COMPILATION 0
#endif

#ifdef ORCA_COMPILATION
#undef ORCA_COMPILATION
#define ORCA_COMPILATION 1
#else
#define ORCA_COMPILATION 0
#endif

#if defined(GY_WASM_STD_LIB)
#undef GY_WASM_STD_LIB
#define GY_WASM_STD_LIB 1
#else
#define GY_WASM_STD_LIB 0
#endif

#if defined(GYLIB_DEBUG_NAMES_ENABLED)
#undef GYLIB_DEBUG_NAMES_ENABLED
#define GYLIB_DEBUG_NAMES_ENABLED 1
#else
#define GYLIB_DEBUG_NAMES_ENABLED 0
#endif

#if defined(GYLIB_MEM_ARENA_DEBUG_ENABLED)
#undef GYLIB_MEM_ARENA_DEBUG_ENABLED
#define GYLIB_MEM_ARENA_DEBUG_ENABLED 1
#else
#define GYLIB_MEM_ARENA_DEBUG_ENABLED 0
#endif

#if PLAYDATE_COMPILATION
#if defined(PLAYDATE_DEVICE) && defined(PLAYDATE_SIMULATOR)
#error Both PLAYDATE_DEVICE and PLAYDATE_SIMULATOR were defined, which is not supported!
#elif defined(PLAYDATE_DEVICE)
#undef PLAYDATE_DEVICE
#define PLAYDATE_DEVICE    1
#define PLAYDATE_SIMULATOR 0
#elif defined(PLAYDATE_SIMULATOR)
#undef PLAYDATE_SIMULATOR
#define PLAYDATE_SIMULATOR 1
#define PLAYDATE_DEVICE    0
#else
#error Either PLAYDATE_DEVICE or PLAYDATE_SIMULATOR must be defined!
#endif
#endif

#if (PLAYDATE_COMPILATION && PLAYDATE_DEVICE) || WASM_COMPILATION
#define PLATFORM_32BIT 1
#define PLATFORM_64BIT 0
#else
#define PLATFORM_32BIT 0
#define PLATFORM_64BIT 1
#endif

#endif //  _GY_DEFINES_CHECK_H

// +--------------------------------------------------------------+
// |                   Autocomplete Dictionary                    |
// +--------------------------------------------------------------+
/*
@Defines
WINDOWS_COMPILATION
OSX_COMPILATION
LINUX_COMPILATION
WASM_COMPILATION
PLAYDATE_COMPILATION
ORCA_COMPILATION
GY_WASM_STD_LIB
GYLIB_DEBUG_NAMES_ENABLED
GYLIB_MEM_ARENA_DEBUG_ENABLED
PLAYDATE_DEVICE
PLAYDATE_SIMULATOR
PLATFORM_32BIT
PLATFORM_64BIT
@Types
@Functions
*/
