/*
File:   gy_standard_names.h
Author: Taylor Robbins
Date:   04\15\2024
*/

#ifndef _GY_STANDARD_NAMES_H
#define _GY_STANDARD_NAMES_H

// +--------------------------------------------------------------+
// |                    Standard People Names                     |
// +--------------------------------------------------------------+
#ifdef GYLIB_NUM_STANDARD_PEOPLE_NAMES
#if (GYLIB_NUM_STANDARD_PEOPLE_NAMES != 10 && GYLIB_NUM_STANDARD_PEOPLE_NAMES != 100 && GYLIB_NUM_STANDARD_PEOPLE_NAMES != 1000)
#error You must #define GYLIB_NUM_STANDARD_PEOPLE_NAMES to be either 10, 100, or 1000
#endif
//https://1000randomnames.com/
const char* GyStandardPeopleNames[GYLIB_NUM_STANDARD_PEOPLE_NAMES] =
{
	"Adrianna Stark",
	"Kristopher Chase",
	"Angie Bautista",
	"Raul Landry",
	"Brynleigh Boyd",
	"Dean Blackwell",
	"Saoirse Terry",
	"Armani Singleton",
	"Malaysia Reynolds",
	"Vincent Bennett",
	#if (GYLIB_NUM_STANDARD_PEOPLE_NAMES > 10)
	"Josephine Howe",
	"Alaric Patrick",
	"Lyra Kennedy",
	"Maxwell Walters",
	"Samara Gallagher",
	"Marcos Rivera",
	"Lillian Dunn",
	"Dawson Hendrix",
	"Zhuri Morrison",
	"Maximus Robles",
	"Felicity Ortiz",
	"Landon Montgomery",
	"Evangeline Pineda",
	"Gerardo Quinn",
	"Heaven Underwood",
	"Reece Roy",
	"Savanna Santos",
	"Walker Weber",
	"Alayah Hernandez",
	"Mason Howell",
	"Mckenna Love",
	"Jeffrey Espinosa",
	"Braylee Rasmussen",
	"Will Stephenson",
	"Khaleesi Roach",
	"Caspian Singh",
	"Vivienne Colon",
	"Bruce Farley",
	"Wrenley Cordova",
	"Vicente Ball",
	"Abby Costa",
	"Kenji Phillips",
	"Naomi Valdez",
	"Kyler Shelton",
	"Makenzie Carey",
	"Watson Grant",
	"Alaina Cortes",
	"Banks Stephens",
	"Millie Nixon",
	"Cory Ball",
	"Abby Donovan",
	"Brayan Hoover",
	"Virginia O’Donnell",
	"Lian Vaughn",
	"Reign Casey",
	"Armando Cook",
	"Aaliyah Hopkins",
	"Ali Salas",
	"Amber Conley",
	"Marvin Roth",
	"Elliot Huff",
	"Finnley Winters",
	"Kataleya Jarvis",
	"Marlon Craig",
	"Brynn Stevenson",
	"Callan Allison",
	"Chelsea Mitchell",
	"Jaxon Spence",
	"Aislinn Hess",
	"Lawrence Cochran",
	"Alma Person",
	"Moses Mullins",
	"Maliyah Cobb",
	"Raphael Patrick",
	"Lyra Donaldson",
	"Canaan Levy",
	"Flora Harrell",
	"Nelson Calhoun",
	"Thalia Adkins",
	"Kylo Vu",
	"Kimora Parker",
	"Caleb Ross",
	"Peyton Hopkins",
	"Ali Valenzuela",
	"Henley Burton",
	"Zander Bonilla",
	"Romina Bautista",
	"Raul Bryant",
	"Parker Mendoza",
	"Dominic Velez",
	"Megan Bradford",
	"Ander Hanson",
	"Mariana Stokes",
	"Santana McFarland",
	"Annika McBride",
	"Denver Chung",
	"Rivka Arnold",
	"Abraham Robinson",
	"Nora Hinton",
	"Frankie Lambert",
	#endif
	#if (GYLIB_NUM_STANDARD_PEOPLE_NAMES > 100)
	"Nina Camacho",
	"Tatum Tucker",
	"Esther Aguirre",
	"Andy Fry",
	"Clarissa Reid",
	"Josue Wagner",
	"Maeve Allison",
	"Dennis Ho",
	"Calliope Duncan",
	"Avery Price",
	"Piper Potter",
	"Lucca Poole",
	"Bonnie McMillan",
	"Rocky Kane",
	"Ellianna Hudson",
	"Peter Manning",
	"Jennifer Wagner",
	"Enzo Cabrera",
	"Daleyza Russell",
	"Weston Browning",
	"Princess Hood",
	"Brixton Price",
	"Piper Goodwin",
	"Kaison Gray",
	"Sarah Page",
	"Pablo Padilla",
	"Maggie Taylor",
	"Jackson Lambert",
	"Nina Shepherd",
	"Ronald Estrada",
	"Sawyer Delgado",
	"Colt Flynn",
	"Dorothy Coleman",
	"Micah Nichols",
	"Aliyah Velazquez",
	"Drew Rodgers",
	"Selah Dodson",
	"Seven Best",
	"Lexie Lane",
	"Matias Boyd",
	"Georgia Rivera",
	"Charles Tate",
	"Skye Hubbard",
	"Forrest Torres",
	"Violet Foley",
	"Mohammad McKinney",
	"Gwendolyn Mendoza",
	"Dominic Jacobs",
	"Camilla Casey",
	"Armando Harrington",
	"Legacy Keith",
	"Jagger Norman",
	"Malani Cannon",
	"Archie Bass",
	"Zahra Enriquez",
	"Elisha Booth",
	"Zariyah Melendez",
	"Nikolas Graves",
	"Elle Murillo",
	"Lance Durham",
	"Tiffany Hardin",
	"Hassan Gray",
	"Sarah Randall",
	"Trenton Vega",
	"Dakota McKay",
	"Joey Gill",
	"Jordan Portillo",
	"Wallace Paul",
	"Daphne Lowery",
	"Jaxxon Beltran",
	"Kaydence West",
	"Diego Ray",
	"Ruth Rogers",
	"Colton Dejesus",
	"Julissa Castaneda",
	"Collin Gibbs",
	"Carter Peralta",
	"Dangelo Leblanc",
	"Novalee Jensen",
	"Cash Velez",
	"Megan Trejo",
	"Wesson Novak",
	"Kaiya Zavala",
	"Dillon Chase",
	"Angie Gregory",
	"Travis Klein",
	"Elianna Roman",
	"Kian King",
	"Victoria Black",
	"Matteo York",
	"Milan Palacios",
	"Thaddeus Melton",
	"Kamiyah Lambert",
	"Mario Meyer",
	"Sara Schmidt",
	"Zayden Nielsen",
	"Vienna Molina",
	"Prince Bell",
	"Melody Spence",
	"Cillian Heath",
	"Amani Morgan",
	"Hunter Livingston",
	"Milena Pollard",
	"Jad Daniel",
	"Joy Villarreal",
	"Nikolai Myers",
	"Lydia Lucas",
	"Chance Vargas",
	"Andrea Wells",
	"Max Ferguson",
	"Juliana Delarosa",
	"Osiris Myers",
	"Lydia Miranda",
	"Rory Dougherty",
	"Alisson Lee",
	"Jack Soto",
	"Brynlee Garcia",
	"James Hill",
	"Hannah Quinn",
	"Rhys McIntosh",
	"Gwen Bernal",
	"Eithan Stout",
	"Chana Lindsey",
	"Jayson Marin",
	"Celia Frost",
	"Dario Lozano",
	"Cecelia Harper",
	"Hayes Kramer",
	"Hanna Edwards",
	"Adrian Fischer",
	"Maci Moreno",
	"Myles Fry",
	"Clarissa Archer",
	"Ephraim Roman",
	"Astrid Freeman",
	"Jayce Washington",
	"Valerie Vang",
	"Jimmy Horne",
	"Marlowe Norris",
	"Cairo Rosario",
	"Louisa Case",
	"Bentlee Burton",
	"Miriam Luna",
	"Erick Kane",
	"Ellianna Torres",
	"Jayden Huang",
	"Francesca Castro",
	"Jasper Carson",
	"Nalani Gaines",
	"Talon Wise",
	"Mira Quinn",
	"Rhys Henry",
	"Summer Keith",
	"Jagger Armstrong",
	"Presley Best",
	"Harlem Vaughn",
	"Reign Watson",
	"Greyson Lu",
	"Emani Brewer",
	"Cruz Perez",
	"Eleanor Horne",
	"Zev Meadows",
	"Pearl McCullough",
	"Briar Avila",
	"Amiyah Trevino",
	"Jaime Alvarez",
	"Leilani Klein",
	"Marco Ramos",
	"Alice Rose",
	"Hayden Richards",
	"Trinity Barry",
	"Emery Hancock",
	"Katelyn Rowland",
	"Eliezer Tang",
	"Belle Murray",
	"Ashton Carey",
	"Alora Snow",
	"Houston Quintana",
	"Kenia Rosales",
	"Wilder Dillon",
	"Laurel Castro",
	"Jasper McLaughlin",
	"Stephanie Jaramillo",
	"Riggs Reyna",
	"Luella Adkins",
	"Kylo Hall",
	"Leah Salinas",
	"Edgar McKenzie",
	"Briar Richardson",
	"Robert Rodriguez",
	"Evelyn Christian",
	"Ledger Faulkner",
	"Ansley Herring",
	"Henrik Beard",
	"Ezra Gibbs",
	"Deacon Reed",
	"Valentina Hodges",
	"Alonzo Ware",
	"Eileen Boone",
	"Mauricio Rodgers",
	"Selah Baldwin",
	"Jaiden Wood",
	"Natalia Williams",
	"Oliver Ingram",
	"Katie Lozano",
	"Boone Mack",
	"Nadia Beasley",
	"Stanley McDaniel",
	"Dahlia Hensley",
	"Layne Rocha",
	"Emmie Fowler",
	"Kameron Medrano",
	"Halle Richmond",
	"Mordechai Ayers",
	"Simone Ray",
	"Arlo Acevedo",
	"Ashlynn Mata",
	"Ray Moon",
	"Naya Lambert",
	"Mario Rivas",
	"Averie Li",
	"Jorge Glenn",
	"Blaire Harmon",
	"Roberto Crawford",
	"Aubree Aguirre",
	"Andy Price",
	"Piper Lin",
	"Conor Robertson",
	"Harmony Robinson",
	"Matthew Ramsey",
	"Lyric Keith",
	"Jagger Bishop",
	"Brooklynn Cano",
	"Terry Dudley",
	"Hadleigh Quinn",
	"Rhys McGee",
	"Kayleigh Calhoun",
	"Gary Ventura",
	"Zora Jarvis",
	"Marlon Sloan",
	"Selene Maynard",
	"Landry Curtis",
	"Alexis Taylor",
	"Jackson Arnold",
	"Finley Gilmore",
	"Vihaan Gill",
	"Jordan McCormick",
	"Jasiah Salinas",
	"Royalty Sandoval",
	"Brantley Steele",
	"Rylie Cannon",
	"Archie Hart",
	"Gemma Dudley",
	"Colter Clark",
	"Chloe Sanders",
	"Jose Hawkins",
	"Ariel Todd",
	"Baylor Dodson",
	"Etta Grant",
	"Leon Johns",
	"Giovanna Foley",
	"Mohammad Hess",
	"Kaliyah Gentry",
	"Magnus Zhang",
	"Sarai Preston",
	"Vincenzo Zamora",
	"Sierra Daugherty",
	"Turner Garza",
	"River Hester",
	"Rene Burke",
	"Vera Ibarra",
	"Asa Bell",
	"Melody Mosley",
	"Rayden Galvan",
	"Dallas Hahn",
	"Kabir Munoz",
	"Kehlani Larson",
	"Rafael Fisher",
	"Arya Zavala",
	"Dillon Quintero",
	"Keyla Hall",
	"Thomas Berry",
	"Annabelle Maddox",
	"Lyric Williamson",
	"Catherine Blackburn",
	"Zahir Bender",
	"Lilyana O’Donnell",
	"Lian Calhoun",
	"Thalia Pollard",
	"Jad Henderson",
	"Maria Mendez",
	"Arthur Ayala",
	"Blair Church",
	"Terrance Mathews",
	"Sloan Walker",
	"Luke Barrett",
	"Kendall Booth",
	"Chaim West",
	"Remi Eaton",
	"Leighton Rivera",
	"Lillian Rhodes",
	"Titus Greene",
	"Selena Pearson",
	"Gunner Mahoney",
	"Promise Alexander",
	"Kingston Cross",
	"Nayeli Person",
	"Moses Nixon",
	"Deborah Calderon",
	"Oakley Dickson",
	"Emmalynn McCarthy",
	"Devin Gill",
	"Jordan Kaur",
	"Augustine Esquivel",
	"Jaylee Serrano",
	"Milan Hurst",
	"Adalee Bartlett",
	"Kace Patrick",
	"Lyra Keith",
	"Jagger Navarro",
	"Winter Rivera",
	"Charles Pena",
	"Rachel Walker",
	"Luke Lozano",
	"Cecelia Pena",
	"Marcus Rojas",
	"Adaline Love",
	"Jeffrey Charles",
	"Jenna Mathis",
	"Gustavo Ali",
	"Zelda Willis",
	"Remington Michael",
	"Aubriella Hughes",
	"Everett Bean",
	"Jenesis Hartman",
	"Baker McBride",
	"Kelsey Pitts",
	"Trey Payne",
	"London Tran",
	"Braxton Gibbs",
	"Carter Adams",
	"Hudson Cisneros",
	"Janelle Moses",
	"Niklaus Galindo",
	"Corinne Acosta",
	"Jensen Case",
	"Cleo Garrison",
	"Noe Vaughan",
	"Nancy Torres",
	"Jayden Singleton",
	"Malaysia Lopez",
	"Michael Bautista",
	"Antonella Wang",
	"Cohen David",
	"Haylee Santiago",
	"Beckham Gregory",
	"Alaya Escobar",
	"Zachariah Combs",
	"Irene Henderson",
	"Beau Le",
	"Myla Dixon",
	"Camden Miller",
	"Isabella Stewart",
	"Nolan Murphy",
	"Bella Everett",
	"Camilo Cardenas",
	"Raven King",
	"Julian Camacho",
	"Armani Klein",
	"Marco Floyd",
	"Yaretzi Crawford",
	"Kevin Kane",
	"Ellianna Duran",
	"Ismael Caldwell",
	"Evelynn Benson",
	"Desmond Black",
	"Molly Reynolds",
	"Vincent Alvarez",
	"Leilani Hobbs",
	"Brendan Salazar",
	"Freya Barron",
	"Dustin Bentley",
	"Jaylin Barajas",
	"Brennan Kaur",
	"Holland Herring",
	"Henrik Benson",
	"Collins Pineda",
	"Gerardo Montes",
	"Roselyn Melendez",
	"Nikolas Zuniga",
	"Leslie Lang",
	"Wells Bentley",
	"Jaylin Owen",
	"Cannon Peterson",
	"Caroline Carroll",
	"Oscar Gardner",
	"Jordyn Stafford",
	"Alfredo Andersen",
	"Zoie Correa",
	"Zakai Clayton",
	"Saige Adkins",
	"Kylo Romero",
	"Eliza McBride",
	"Denver Tanner",
	"Harmoni Duran",
	"Ismael Frederick",
	"Sariyah Flynn",
	"Kannon McFarland",
	"Annika Houston",
	"Sylas Pollard",
	"Marisol Huang",
	"Ayaan Pacheco",
	"Paris Richmond",
	"Mordechai Evans",
	"Eliana Bradley",
	"Richard Lugo",
	"Kaylie Barr",
	"Harley Herman",
	"Paulina Hartman",
	"Baker Lowe",
	"Amari Reynolds",
	"Vincent Gallagher",
	"Elliott Sosa",
	"Emir Calderon",
	"Serena Waters",
	"Maximilian Lawrence",
	"Lauren Clayton",
	"Boston Watkins",
	"Lola Kelly",
	"Cooper Tate",
	"Skye Black",
	"Matteo Hampton",
	"Leona Waller",
	"Marley Bradshaw",
	"Berkley Golden",
	"Amias Barber",
	"Cassidy Vang",
	"Jimmy Adkins",
	"Emelia Osborne",
	"Augustus Carey",
	"Alora Phelps",
	"Hamza Griffith",
	"Alicia Duarte",
	"Abdullah Kelly",
	"Ruby Barrett",
	"Angelo Fitzgerald",
	"Marlee Curtis",
	"Muhammad Diaz",
	"Elena Gaines",
	"Talon Fisher",
	"Arya Page",
	"Pablo Dillon",
	"Laurel Raymond",
	"Maurice Stout",
	"Chana Lam",
	"Bodie Hail",
	"Lainey Daniel",
	"Grady Ryan",
	"Morgan Li",
	"Jorge Golden",
	"Giuliana Wolfe",
	"Donovan Jefferson",
	"Julieta Phan",
	"Maison Williamson",
	"Catherine Kirk",
	"Alessandro Serrano",
	"Allie Waller",
	"Marley Hendrix",
	"Zhuri Ruiz",
	"Austin Klein",
	"Elianna Winters",
	"Deandre Garza",
	"River Yates",
	"Braylon Stone",
	"Catalina Yang",
	"Malcolm Reilly",
	"Tori Salinas",
	"Edgar Marquez",
	"Milani Hill",
	"Isaac Reyes",
	"Audrey Stein",
	"Creed Barton",
	"Danna Hickman",
	"Jakobe Park",
	"Lia Jacobs",
	"Bryan Palacios",
	"Bria Sawyer",
	"Jefferson Peters",
	"Leila Gaines",
	"Talon Willis",
	"Alexa Hess",
	"Lawrence George",
	"Adelyn Ochoa",
	"Winston Sosa",
	"Cassandra Conner",
	"Phillip Hartman",
	"Kennedi Wong",
	"Walter Jimenez",
	"Adeline Mann",
	"Nehemiah Ochoa",
	"Luciana Buck",
	"Jon Cooper",
	"Serenity Farmer",
	"Jamison Cohen",
	"Destiny Ramirez",
	"David Dougherty",
	"Alisson Meyer",
	"Tristan Nunez",
	"Mya Simon",
	"Zayne Potter",
	"Rory Corona",
	"Darian Mosley",
	"Zaniyah James",
	"Jaxson Hayden",
	"Avayah Webster",
	"Shawn Munoz",
	"Kehlani Tyler",
	"Emmitt Molina",
	"Alexandria Chambers",
	"Orion Branch",
	"Luisa Gonzales",
	"Brayden Santana",
	"Myra Fowler",
	"Kameron Jordan",
	"Adalynn Bradford",
	"Ander Bowen",
	"Dream Warren",
	"Abel Barnett",
	"Harlow Fox",
	"Antonio English",
	"Kelly McMahon",
	"Jakob Tate",
	"Skye Sparks",
	"Drake Tucker",
	"Esther Daniel",
	"Grady Jenkins",
	"Rylee Alexander",
	"Kingston May",
	"Adriana Owen",
	"Cannon Salgado",
	"Avalynn Thornton",
	"Malik Hobbs",
	"Lacey Swanson",
	"Hugo Shaffer",
	"Alanna Lowery",
	"Jaxxon Parks",
	"Ainsley Crawford",
	"Kevin Palacios",
	"Bria Hill",
	"Isaac Avila",
	"Amiyah Ferguson",
	"Miguel Dalton",
	"Lilian Stewart",
	"Nolan Murray",
	"Faith Lawrence",
	"Kaleb Harper",
	"Ana McLean",
	"Crosby Faulkner",
	"Ansley McKee",
	"Bjorn Richards",
	"Trinity Middleton",
	"Misael Cano",
	"Egypt Rich",
	"Miller Kerr",
	"Baylee Andrews",
	"Lukas Mahoney",
	"Promise Yoder",
	"Johan Levy",
	"Flora Salinas",
	"Edgar Calderon",
	"Serena Costa",
	"Kenji Felix",
	"Paisleigh Duncan",
	"Avery Melton",
	"Kamiyah Lozano",
	"Boone Holt",
	"Adelynn Benjamin",
	"Kyro Knox",
	"Kallie Tapia",
	"Samir Simpson",
	"Anastasia Garrett",
	"Kairo Jensen",
	"Jane Quintero",
	"Thatcher Young",
	"Zoey Crosby",
	"Tristen Merritt",
	"Kaisley Villa",
	"Clay Clarke",
	"Kaitlyn Parrish",
	"Karsyn Boone",
	"Mariam Pratt",
	"Rowen Hendrix",
	"Zhuri Kirby",
	"Tony Roach",
	"Lyanna Boyd",
	"Dean Cruz",
	"Claire Sanchez",
	"Joseph Bernal",
	"Emmeline Kline",
	"Ramon Rivers",
	"Kiana Abbott",
	"Kohen Barnes",
	"Liliana Duarte",
	"Abdullah Zimmerman",
	"Ariyah Reid",
	"Josue Lugo",
	"Kaylie Scott",
	"Leo Ortega",
	"Lilah McKee",
	"Bjorn Valdez",
	"Diana Ingram",
	"Tripp Fowler",
	"Lennon Guerra",
	"Leland Bravo",
	"Amoura Vang",
	"Jimmy Villanueva",
	"Monroe Moreno",
	"Myles Meyer",
	"Sara Berger",
	"Byron Cabrera",
	"Daleyza Bonilla",
	"Aden Noble",
	"Hunter Armstrong",
	"Grant Steele",
	"Rylie Mathews",
	"Jamir King",
	"Victoria Solis",
	"Ronin Jenkins",
	"Rylee Bennett",
	"Leonardo Summers",
	"Frankie Roman",
	"Kian Sexton",
	"Ellen Castro",
	"Jasper Callahan",
	"Kimber Yu",
	"Bryant Davidson",
	"Jayla Rogers",
	"Colton Lester",
	"Averi Bowen",
	"Trevor Vaughn",
	"Reign McPherson",
	"Foster Escobar",
	"Erin Cameron",
	"Rayan McKenzie",
	"Briar McCormick",
	"Jasiah Foster",
	"Brielle Lloyd",
	"Zaire Knight",
	"Gracie Duffy",
	"Kyng May",
	"Adriana O’Neal",
	"Eddie Jefferson",
	"Julieta Case",
	"Bentlee Dean",
	"Julianna Wiley",
	"Mathew Vaughn",
	"Reign Chung",
	"Ira Keith",
	"Elyse Walters",
	"Colson Soto",
	"Brynlee Cruz",
	"Ryan Meyers",
	"Leyla Fernandez",
	"Bentley Huang",
	"Francesca Duke",
	"Kalel Reese",
	"Rosemary Rivers",
	"Bear Hawkins",
	"Ariel Kramer",
	"Kylan Villalobos",
	"Zoya Suarez",
	"Soren Parrish",
	"Tiana Sims",
	"Brian Frazier",
	"Octavia Banks",
	"Martin Merritt",
	"Kaisley Page",
	"Pablo Short",
	"Cheyenne Mitchell",
	"Jaxon Hale",
	"Brinley Schultz",
	"Cody Bradshaw",
	"Berkley Fields",
	"Clayton Villa",
	"Johanna Rivers",
	"Bear Fox",
	"Juliette Petersen",
	"Samson Hoffman",
	"Aspen Durham",
	"Kellen Day",
	"Hayden Ball",
	"Shane Salgado",
	"Avalynn Robertson",
	"Emiliano Cardenas",
	"Raven Ellison",
	"Kye Stafford",
	"Bridget Patterson",
	"Amir Valdez",
	"Diana Mercado",
	"Abram Parks",
	"Ainsley Woodard",
	"Westley Harrington",
	"Legacy Cardenas",
	"Johnathan Carey",
	"Alora Romero",
	"Bryson Wilkinson",
	"Siena Cardenas",
	"Johnathan Fleming",
	"Fatima Hodge",
	"Reign Tanner",
	"Harmoni Gardner",
	"Alan Allen",
	"Riley Perez",
	"Owen Mills",
	"June Franco",
	"Gage Knapp",
	"Linda Austin",
	"Omar Trevino",
	"Priscilla Frost",
	"Dario Chambers",
	"Makayla Reynolds",
	"Vincent Wilcox",
	"Ashlyn Boyle",
	"Robin Ford",
	"Alexandra Campbell",
	"Christopher Corona",
	"Marianna Navarro",
	"Reid Rose",
	"Magnolia Donaldson",
	"Canaan Henderson",
	"Maria Pratt",
	"Rowen Potter",
	"Rory Daugherty",
	"Turner Mahoney",
	"Promise McDonald",
	"Calvin Hensley",
	"Malaya Sheppard",
	"Trent Everett",
	"Noah Munoz",
	"Justin Quintana",
	"Kenia Norman",
	"Aziel Ramos",
	"Alice Glenn",
	"Zaid O’Connor",
	"Charli Peck",
	"Yousef Levy",
	"Flora Matthews",
	"Preston Stanley",
	"Gracelyn Portillo",
	"Wallace Gomez",
	"Natalie Ball",
	"Shane Santana",
	"Myra Powell",
	"Bennett Ellison",
	"Raina Garrett",
	"Kairo Parker",
	"Aubrey Webb",
	"Lorenzo Hensley",
	"Malaya Stephenson",
	"Joe Hamilton",
	"Mackenzie Wilkinson",
	"Leonard Ashley",
	"Khalani Hamilton",
	"Jason Keller",
	"Logan Hobbs",
	"Brendan Wagner",
	"Maeve Dickson",
	"Maxton Doyle",
	"Annalise O’Donnell",
	"Lian Rowe",
	"Matilda Schultz",
	"Cody Morse",
	"Kairi Bailey",
	"Axel Jennings",
	"Palmer Townsend",
	"Alexis Palacios",
	"Bria Park",
	"Daxton Guerrero",
	"Margot Bowers",
	"Dorian Tucker",
	"Esther Salas",
	"Zaiden Daniels",
	"Ember Valdez",
	"Kyler Acevedo",
	"Ashlynn Rich",
	"Miller Tanner",
	"Harmoni Walters",
	"Colson Lester",
	"Averi Lane",
	"Matias Smith",
	"Olivia Perkins",
	"Kyrie Boyd",
	"Georgia Johnston",
	"Felix Flowers",
	"Ariya Clayton",
	"Boston Waters",
	"Bristol Wallace",
	"Chase Rogers",
	"Madelyn Hinton",
	"Frankie Pierce",
	"Arabella Poole",
	"Quincy Duran",
	"Willa Valencia",
	"Dax Powell",
	"Vivian Chen",
	"Emmanuel Zamora",
	"Sierra Estes",
	"Hakeem Larson",
	"Alayna Fitzgerald",
	"Peyton Lester",
	"Averi Franco",
	"Gage Torres",
	"Violet Horton",
	"Garrett Bryan",
	"Meredith Trejo",
	"Wesson Avila",
	"Amiyah Green",
	"Anthony Mayer",
	"Ainhoa Stanley",
	"Manuel Olson",
	"Isabel Sandoval",
	"Brantley Carrillo",
	"Kaylani Pratt",
	"Rowen Salas",
	"Amber Nicholson",
	"Rodrigo Sandoval",
	"Elsie Christian",
	"Ledger Villarreal",
	"Jazlyn Owen",
	"Cannon Sawyer",
	"Marina Faulkner",
	"Jabari Barker",
	"Remington Willis",
	"Remington Davenport",
	"Adrianna Savage",
	"Keaton Wang",
	"Kailani Henderson",
	"Beau Torres",
	"Violet Henderson",
	"Beau Leal",
	"Murphy Richards",
	"Holden Snyder",
	"Callie Salinas",
	"Edgar Powers",
	"Michelle Fowler",
	"Kameron Gomez",
	"Natalie Cannon",
	"Archie Salgado",
	"Avalynn Patel",
	"Parker Drake",
	"Jayleen Castaneda",
	"Collin Osborne",
	"Shelby Campos",
	"Gideon Escobar",
	"Erin Stout",
	"Callahan Holt",
	"Adelynn Sosa",
	"Emir Farley",
	"Wrenley Duarte",
	"Abdullah McClure",
	"Estella Bond",
	"Roger Roy",
	"Savanna Burgess",
	"Kolton Clark",
	"Chloe Day",
	"Kayson Shepard",
	"Noor Blankenship",
	"Ernesto Rosario",
	"Louisa Hahn",
	"Kabir McIntosh",
	"Gwen Lozano",
	"Boone Campbell",
	"Addison Clayton",
	"Boston Cuevas",
	"Adele Torres",
	"Jayden McIntyre",
	"Rebekah Li",
	"Jorge Friedman",
	"Aspyn Mullen",
	"Shepard Cline",
	"Lina Carter",
	"Maverick Newton",
	"Braelynn Macias",
	"Moshe Stout",
	"Chana Kane",
	"Brock Collins",
	"Kinsley Serrano",
	"Milan Oliver",
	"Camille Harrington",
	"Omari Kirk",
	"Ellis Good",
	"Davian Rangel",
	"Gloria Hodge",
	"Reign Bartlett",
	"Aubrielle Paul",
	"Noel Luna",
	"Journey George",
	"Mark Jefferson",
	"Julieta Richards",
	"Holden Huber",
	#endif
};
#endif // GYLIB_NUM_STANDARD_PEOPLE_NAMES

const char* GetStandardPeopleName(u64 nameIndex)
{
	#ifdef GYLIB_NUM_STANDARD_PEOPLE_NAMES
	return GyStandardPeopleNames[nameIndex % GYLIB_NUM_STANDARD_PEOPLE_NAMES];
	#else
	UNUSED(nameIndex);
	return "John Doe";
	#endif
}

// +--------------------------------------------------------------+
// |                     Standard Rock Names                      |
// +--------------------------------------------------------------+
#ifdef GYLIB_NUM_STANDARD_ROCK_NAMES
#if (GYLIB_NUM_STANDARD_ROCK_NAMES != 10 && GYLIB_NUM_STANDARD_ROCK_NAMES != 100)
#error You must #define GYLIB_NUM_STANDARD_ROCK_NAMES to be either 10 or 100
#endif
//https://en.wikipedia.org/wiki/List_of_rock_types
const char* GyStandardRockNames[GYLIB_NUM_STANDARD_ROCK_NAMES] =
{
	"Adakite",
	"Andesite",
	"Anorthosite",
	"Aplite",
	"Argillite",
	"Arkose",
	"Basalt",
	"Basanite",
	"Blairmorite",
	"Boninite",
	#if (GYLIB_NUM_STANDARD_ROCK_NAMES > 10)
	"Breccia",
	"Calcarenite",
	"Carbonatite",
	"Chalk",
	"Charnockite",
	"Chert",
	"Claystone",
	"Coal",
	"Conglomerate",
	"Coquina",
	"Dacite",
	"Diabase",
	"Diamictite",
	"Diatomite",
	"Diorite",
	"Dolomite",
	"Dunite",
	"Essexite",
	"Evaporite",
	"Flint",
	"Foidolite",
	"Gabbro",
	"Geyserite",
	"Granite",
	"Granodiorite",
	"Granophyre",
	"Greywacke",
	"Gritstone",
	"Harzburgite",
	"Hornblendite",
	"Hyaloclastite",
	"Icelandite",
	"Ignimbrite",
	"Ijolite",
	"Itacolumite",
	"Jaspillite",
	"Kimberlite",
	"Komatiite",
	"Lamproite",
	"Lamprophyre",
	"Laterite",
	"Latite",
	"Lherzolite",
	"Lignite",
	"Limestone",
	"Marl",
	"Monzogranite",
	"Monzonite",
	"Mudstone",
	"Nephelinite",
	"Norite",
	"Obsidian",
	"Oolite",
	"Pegmatite",
	"Peridotite",
	"Phonolite",
	"Phonotephrite",
	"Phosphorite",
	"Picrite",
	"Porphyry",
	"Pumice",
	"Pyroxenite",
	"Quartz",
	"Quartzolite",
	"Rhyodacite",
	"Rhyolite",
	"Sandstone",
	"Scoria",
	"Shale",
	"Shonkinite",
	"Siltstone",
	"Sovite",
	"Syenite",
	"Sylvinite",
	"Tachylyte",
	"Tephriphonolite",
	"Tephrite",
	"Tillite",
	"Tonalite",
	"Trachyandesite",
	"Trachybasalt",
	"Trachyte",
	"Travertine",
	"Troctolite",
	"Trondhjemite",
	"Tufa",
	"Turbidite",
	"Wackestone",
	"Websterite",
	"Wehrlite",
	#endif
};
#endif //GYLIB_NUM_STANDARD_ROCK_NAMES

const char* GetStandardRockName(u64 nameIndex)
{
	#ifdef GYLIB_NUM_STANDARD_ROCK_NAMES
	return GyStandardRockNames[nameIndex % GYLIB_NUM_STANDARD_ROCK_NAMES];
	#else
	UNUSED(nameIndex);
	return "Quartz";
	#endif
}

#endif //  _GY_STANDARD_NAMES_H

// +--------------------------------------------------------------+
// |                   Autocomplete Dictionary                    |
// +--------------------------------------------------------------+
/*
@Defines
GYLIB_NUM_STANDARD_PEOPLE_NAMES
GYLIB_NUM_STANDARD_ROCK_NAMES
@Globals
GyStandardPeopleNames
GyStandardRockNames
@Functions
const char* GetStandardPeopleName(u64 nameIndex)
const char* GetStandardRockName(u64 nameIndex)
*/
